### ISSUE TITLE
关于combineReducers&compose

### ISSUE THREAD

**Issue by yaolei** [kenberkeley/redux-simple-tutorial#12]
不好意思，本来想单独要下联系方式，可是按您说的还是开issue吧。
关于combineReducers&compose 的介绍部分没有看懂有几个疑惑
1.compose 的应用场景一般是什么？我理解的是，这个函数只是在调用方法的执行顺序上有所不同，像Jquery的链式调用，但是compose 是从右向左调用，具体在什么时候应该用这个函数？
2.combineReducers 这个实在没看懂，这个函数是将多个state整合吗？
方便的话说明下具体的在什么时候用到，谢谢

**Comment by yaolei** [comment]
哦，还有，我本来是想通过rest api的请求获取返回值的功能，不知道选用redux做是否正确

**Comment by kenberkeley** [comment]
1. 初学者一般用不上 compose，毕竟这是函数式编程的写法
2. `combineReducers` ，顾名思义就是 combine 各 reducer，具体还请看教程，相信我已经说得很明白了
3. Redux 和 RESTful API 没有明显的关系

**Comment by yaolei** [comment]
谢谢您的回复.
1.我没有看过`flux`，是否需要去恶补一下才能更好的了解redux？
2.对于Redux，我想您肯定也在项目中应用过，一般是在什么场景下使用这个？

**Comment by kenberkeley** [comment]
1. 若看完本教程后您还是不了解 Redux 的话，那也只能算是我写得不够细致详尽。但一般是不需要先学 Flux 再学 Redux 的
2. 很难说什么场景适合什么场景不适合，适合自己才是最舒服的。如果您觉得 Redux 太复杂了，大可不必用上
