### ISSUE TITLE
感谢信

### ISSUE THREAD

**Issue by zhaihaoran** [kenberkeley/redux-simple-tutorial#16]
在作者深入浅出的讲解下， 终于是理清楚了redux的思想本质。真的十分感谢！！

**Comment by kenberkeley** [comment]
You are welcome!

**Comment by m26597** [comment]
I've read the whole document but still be confused. I think that the article is enough clear but I couldn't master the redux totally. It is maybe  because of the lack experience during my coding life. Anyway, thanks!

**Comment by acmu** [comment]
果真有感谢信，我刚看完也想写一封，教程真的很好，谢谢
