### ISSUE TITLE
lodash中的deepClone不存在

### ISSUE THREAD

**Issue by zsf513** [kenberkeley/redux-simple-tutorial#4]
你好，根据你这个文档，我学着敲了下代码做为练习，却发现lodash中没有deepClone方法，而有cloneDeep方法，不知道是不是用的lodash版本不同，我用的是lodash4.15.0，redux3.5.2。

**Comment by kenberkeley** [comment]
@zsf513 谢谢您的反馈 已经改正 [49a1f5e](https://github.com/kenberkeley/redux-simple-tutorial/commit/49a1f5e20dc114041df458159fd9af562a5161d0)
