### ISSUE TITLE
写的太好了

### ISSUE THREAD

**Issue by fff89** [kenberkeley/redux-simple-tutorial#5]
这是我见过最好的 redux的文章啦，如果能有  和react配合的教程就好啦，

**Comment by kenberkeley** [comment]
@fengbjhqs 
React 不乏好教程，因此也免得班门弄斧了

**Comment by wangmoumei** [comment]
todo、counter例子见过无数，终于在这篇教程里看懂了redux，应该推广给更多的前端菜鸟们！支持一下！

**Comment by kenberkeley** [comment]
@wangmoumei 
我现在一看到 TODO 就怕了哈哈哈，的确有种隔靴搔痒的赶脚
