### ISSUE TITLE
createStore 部分有点儿小问题...

### ISSUE THREAD

**Issue by BuptStEve** [kenberkeley/redux-simple-tutorial#7]
``` javascript
// 逐个触发回调函数。这里不缓存数组长度是明智的，原因见【悬念1·解疑】
for (var i = 0; i < listeners.length; i++) {
  listeners[i]()
}
```
### 1. 不缓存数组长度和触发回调函数没关系

> 这样的话，dispatch 后，在逐个执行回调函数的过程中  
> 如果有新增订阅或取消订阅，都在 nextListeners 中操作  
> 让 currentListeners 中的回调函数得以完整地执行

就像你之前说的那样，currentListeners 数组在调用回调函数时并不会变化，新增或取消都在 nextListeners 中操作。

[倒是之前都是用 forEach 结果因为 forEach 会对空的子元素进行特殊处理，而改成了 for 循环](https://github.com/reactjs/redux/commit/5b586080b43ca233f78d56cbadf706c933fefd19?diff=split) 
### 2. [`listeners[i]()` 会导致 listeners 作为 this 暴露到外部](https://github.com/reactjs/redux/commit/8e82c15f1288a0a5c5c886ffd87e7e73dc0103e1)

所以现在是这样...

``` javascript
for (var i = 0; i < listeners.length; i++) {
  var listener = listeners[i]
  listener()
}
```

**Comment by kenberkeley** [comment]
感谢您的反馈，已经[修正](https://github.com/kenberkeley/redux-simple-tutorial/commit/d672c65d62464a74afc8adf89263a5069cac5924)

同时在此给出 [JS Bin](https://jsbin.com/sobavo/edit?js,console) 解释暴露 `listeners` 的潜在威胁：

```
var listeners = [ function() { return this; } ]
console.log( listeners[0]() === listeners ); // true

var tmp = listeners[0]; // 引入中间变量
console.log( tmp() === window ); // true

/******** 下面我们来看看泄露 listeners 本体的严重性 ********/

var listeners = [
  function() {
    this.length = 0; // 直接修改数组长度
  }
];
listeners[0]();
console.log( listeners ); // []，篡改成功
```
