### ISSUE TITLE
这里是不是有点不妥

### ISSUE THREAD

**Issue by ibufu** [kenberkeley/redux-simple-tutorial#8]
// 串联各个中间件，为各个中间件传入原 store.dispatch，见【降低逼格写法】的【锚点-2】
      dispatch = compose(...chain)(store.dispatch)
应该是给最后的中间件传入原 store.dispatch。其它的中间件并没有使用原 store.dispatch。

**Comment by kenberkeley** [comment]
衷心感谢！
见 https://github.com/kenberkeley/redux-simple-tutorial/commit/f44785d7139cb6ee046208b0eea961896cf1dcee
